before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

language: objective-c
script: xcodebuild -target 'Bit Slicer Tests' -scheme 'Release' test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
